name: release
on:
  schedule:
    - cron: "10 10 1-31/2 * *"
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out project files
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check and release
        run: |
          sudo apt-get install -y p7zip-full
          repos="Qv2ray/Qv2ray"
          Qlatest_version=$(curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
          -s "https://api.github.com/repos/$repos/tags" \
          --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
          echo $Qlatest_version
          
          DIST_TAGS_URL="https://api.github.com/repos/${{ github.repository }}/tags"
          DIST_TAG_FOUND=`curl -H "Accept: application/vnd.github.v3+json" -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" -s ${DIST_TAGS_URL} --connect-timeout 5 | grep "\"name\"\: \"${Qlatest_version}\""` || true

          
          if [ -z ${DIST_TAG_FOUND} ]; then
            rm -rf *

            wget https://github.com/$repos/releases/download/$Qlatest_version/Qv2ray.$Qlatest_version.Windows-x64.7z
            7z x Qv2ray.$Qlatest_version.Windows-x64.7z && rm Qv2ray.$Qlatest_version.Windows-x64.7z

            repos="v2fly/v2ray-core"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget https://github.com/$repos/releases/download/$latest_version/v2ray-windows-64.zip
            mkdir -p ./deployment/config/vcore
            unzip v2ray-windows-64.zip -d ./deployment/config/vcore && rm v2ray-windows-64.zip 
            
            repos="XTLS/Xray-core"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget https://github.com/$repos/releases/download/$latest_version/Xray-windows-64.zip
            mkdir tmp1
            unzip Xray-windows-64.zip -d ./tmp1
            cp ./tmp1/xray.exe ./deployment/config/vcore
            rm -rf ./tmp1 Xray-windows-64.zip

            repos="Qv2ray/QvPlugin-Trojan"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget -O ./deployment/plugins/trojan.dll https://github.com/$repos/releases/download/$latest_version/QvPlugin-Trojan.$latest_version.Windows-x64.dll

            repos="Qv2ray/QvPlugin-SSR"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget -O ./deployment/plugins/ssr.dll https://github.com/$repos/releases/download/$latest_version/QvPlugin-SSR.$latest_version.Windows-x64.dll

            repos="Qv2ray/QvPlugin-NaiveProxy"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget -O ./deployment/plugins/naiveproxy.dll https://github.com/$repos/releases/download/$latest_version/QvPlugin-NaiveProxy.$latest_version.Windows-x64.dll

            repos="Qv2ray/QvPlugin-Trojan-Go"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget -O ./deployment/plugins/trojan-go.dll https://github.com/$repos/releases/download/$latest_version/QvPlugin-TrojanGo.$latest_version.Windows-x64.dll

            repos="Qv2ray/QvPlugin-SS"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget -O ./deployment/plugins/ss.dll https://github.com/$repos/releases/download/$latest_version/QvPlugin-SS.$latest_version.Windows-x64.dll

            repos="Qv2ray/QvPlugin-Command"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget -O ./deployment/plugins/command.dll https://github.com/$repos/releases/download/$latest_version/QvPlugin-Command.$latest_version.Windows-x64.dll
            
            repos="p4gefau1t/trojan-go"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget https://github.com/$repos/releases/download/$latest_version/trojan-go-windows-amd64.zip
            unzip trojan-go-windows-amd64.zip -d ./deployment/config/vcore && rm trojan-go-windows-amd64.zip 



            repos="klzgrad/naiveproxy"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget https://github.com/$repos/releases/download/$latest_version/naiveproxy-$latest_version-win-x64.zip
            unzip naiveproxy-$latest_version-win-x64.zip -d ./deployment/config/vcore && rm naiveproxy-$latest_version-win-x64.zip
            
            mv ./deployment ./qv2ray.portable
            rm -rf ./qv2ray.portable/config/vcore/example
            cp ./qv2ray.portable/config/vcore/naiveproxy-$latest_version-win-x64/naive.exe ./qv2ray.portable/config/vcore
            rm -rf ./qv2ray.portable/config/vcore/naiveproxy-$latest_version-win-x64
            rm ./qv2ray.portable/config/vcore/*.json
            rm *.zip
            7z a -t7z ./qv2ray-${Qlatest_version}.7z ./qv2ray.portable
            cp ./qv2ray-${Qlatest_version}.7z ./qv2ray.7z
            sha256sum ./qv2ray-${Qlatest_version}.7z > sha256sum-${Qlatest_version}.txt
            sha256sum ./qv2ray.7z > sha256sum.txt
            
            git add .
            git config user.name "Scaleya"
            git config user.email "61817665+Scaleya@users.noreply.github.com"
            git commit -m "Version ${Qlatest_version}"
            git tag -a "${Qlatest_version}" -m "Version ${Qlatest_version}"
            git remote add release "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push -u --follow-tags release main
          fi
