name: release
on:
  schedule:
    - cron: "10 10 1-31/2 * *"
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out project files
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check and release
        run: |
          sudo apt-get install -y p7zip-full
          repos="Qv2ray/Qv2ray"
          Qlatest_version=$(curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
          -s "https://api.github.com/repos/$repos/tags" \
          --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
          echo $Qlatest_version
          
          DIST_TAGS_URL="https://api.github.com/repos/${{ github.repository }}/tags"
          DIST_TAG_FOUND=`curl -H "Accept: application/vnd.github.v3+json" -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" -s ${DIST_TAGS_URL} --connect-timeout 5 | grep "\"name\"\: \"${Qlatest_version}\""` || true

          
          if [ -z ${DIST_TAG_FOUND} ]; then
            rm -rf *

            wget https://github.com/$repos/releases/download/$Qlatest_version/Qv2ray.$Qlatest_version.Windows-x64.7z
            7z e Qv2ray.$Qlatest_version.Windows-x64.7z && rm Qv2ray.$Qlatest_version.Windows-x64.7z

            repos="v2fly/v2ray-core"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget https://github.com/$repos/releases/download/$latest_version/v2ray-windows-64.zip
            unzip v2ray-windows-64.zip -d /deployment/ && rm v2ray-windows-64.zip 

            repos="Qv2ray/QvPlugin-Trojan"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget -O /deployment/plugins/trojan.dll https://github.com/$repos/releases/download/$latest_version/QvPlugin-Trojan.$latest_version.Windows-x64.dll

            zip –q –r -m qv2ray-${Qlatest_version}.zip /deployment

            git add .
            git config user.name "Scaleya"
            git config user.email "61817665+Scaleya@users.noreply.github.com"
            git commit -m "Version ${Qlatest_version}"
            git tag -a "${Qlatest_version}" -m "Version ${Qlatest_version}"
            git remote add release "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push -u --follow-tags release master
          fi
